CREATE TABLE [dbo].[Advertiser]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	[Name] NVARCHAR (100) NOT NULL
)
GO

CREATE UNIQUE INDEX UIDX_NAME ON [dbo].[Advertiser] ([Name])
GO

CREATE FULLTEXT CATALOG [Ft_Advertiser] WITH ACCENT_SENSITIVITY = ON
AS DEFAULT
GO

CREATE FULLTEXT INDEX ON [dbo].[Advertiser]([Name])
KEY INDEX UIDX_NAME ON [Ft_Advertiser]
GO


